# Generated by Django 4.0.3 on 2023-01-07 18:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_advertisement_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='cost',
            field=models.DecimalField(decimal_places=2, error_messages={'min_value': "Cost can't be less than 0.01"}, max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0.01'))]),
        ),
    ]
